# Generated by Django 4.2.4 on 2023-09-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='wishlist',
            new_name='user',
        ),
    ]
